spring:
  application:
    name: edtech
  datasource:
    url: jdbc:mysql://localhost:3306/edtech
    username: root
    password: 12345678
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  jpa-hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8081